services:
  hydra:
    image: oryd/hydra:v2.3.0
    ports:
      - 4444:4444 # Public port
      - 4444:4445 # Admin port
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:4445/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
